// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import { defineConfig, env } from 'prisma/config';


const envFile =
    process.env.NODE_ENV === 'production' ? '.env' : '.env.development';
dotenv.config({ path: envFile });

const databaseUrl = process.env.DATABASE_URL?.trim();
if (!databaseUrl) {
    throw new Error('DATABASE_URL is required');
}

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'src/database/migrations',
    },
    datasource: {
        url: env('DATABASE_URL'),
    },
});
